title: CU-DBMI
subtitle: CU Department of Biomedical Informatics
description: An engaging 1-3 sentence description of your lab.
header: images/background.jpg
footer: images/background.jpg
links:
  github: CU-DBMI
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@CU-DBMI.com
github: CU-DBMI
twitter: CU-DBMI
instagram: CU-DBMI
youtube: CU-DBMI
